---
title: "p8105_hw2_ab4797"
author: "Ani Bilazarian"
date: "10/1/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

# Problem 1

_ Import and Clean Trash Wheel Data

```{r import trash wheel data}
trash_wheel = read_excel("data/trash_wheel_updated.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N408") %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(sports_balls = as.integer(round(sports_balls))) %>% 
rename ("weight" = weight_tons, "volume" = volume_cubic_yards)
```

_ Cleaning precipitation data 2018 and adding the variable 'Year'

```{r read and clean precip 18 data}
precip_18 = read_excel("data/trash_wheel_updated.xlsx", sheet = "2018 Precipitation", range = "A2:B14") %>% 
    janitor::clean_names() %>% 
    drop_na() %>% 
    mutate(year = 2018) %>% 
    mutate(month = month.name[month])
```

_ Cleaning precipitation data 2017 and adding the variable 'Year'

```{Import, Clean, and Combine precip 17}
precip_17 = read_excel("data/trash_wheel_updated.xlsx", sheet = "2017 Precipitation", range = "A2:B14") %>% 
    janitor::clean_names() %>% 
    drop_na() %>% 
    mutate (year = 2017) %>% 
    mutate(month = month.name[month]) 

precip_1718 = bind_rows(precip_17, precip_18)
```

# Problem 2

_ Import & Clean Pols data

```{r read in pols data}
pols_month = read_csv("./data/pols-month.csv", col_types = "cciiiciii") %>% 
  janitor::clean_names() %>% 
  separate("mon", into = c("year", "month", "day")) %>% 
  mutate(month = month.name[as.integer(month)]) %>% 
  rename("gop" = prez_gop, "dem" = prez_dem) %>% 
  select(-day)
```
_ Cleaning SNP data

```{r read in SNP data}
snp = read_csv("./data/snp.csv", col_types = "cd") %>% 
  janitor::clean_names() %>% 
  separate("date", into = c("day", "month", "year")) %>% 
  select("year", "month", "day", "close") %>% 
  mutate(month = month.name[as.integer(month)]) %>% 
  select(-day)
```

_ Cleaning unemployment data

```{r read in unemployment data}
unemployment_data = read_csv("./data/unemployment.csv", col_types = "cdddddddddddd") %>%     janitor::clean_names() %>% 
    pivot_longer (jan:dec, names_to = "month", values_to = "count") 
```

_ Merging SNP into pols 

```{r}
snp_pols_merge = left_join(pols_month, snp, by = c("month", "year"))
snp_pols_unemployment_merge = left_join(snp_pols_merge, unemployment_data, by = c("month", "year"))
```


